# Get the latest Git tag and commit information
execute_process(
    COMMAND git describe --tags --abbrev=0
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE LAST_TAG
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE TAG_RESULT
)

if(TAG_RESULT EQUAL 0)
    execute_process(
        COMMAND git rev-list --count ${LAST_TAG}..HEAD
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE COMMITS_SINCE_TAG
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
else()
    execute_process(
        COMMAND git rev-list --count HEAD
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE COMMITS_SINCE_TAG
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
endif()

# Get the short commit hash
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE COMMIT_HASH_SHORT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get the date of the latest commit
execute_process(
    COMMAND git log -1 --format=%cd --date=short
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE COMMIT_DATE
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(TAG_RESULT EQUAL 0 AND COMMITS_SINCE_TAG STREQUAL "0")
    # Exactly at tag
    string(REGEX MATCH "v([0-9]+)\\.([0-9]+)\\.([0-9]+)" _ ${LAST_TAG})
    set(APP_MAJOR_VERSION ${CMAKE_MATCH_1})
    set(APP_MINOR_VERSION ${CMAKE_MATCH_2})
    set(APP_PATCH_VERSION ${CMAKE_MATCH_3})
    set(APP_DEV_VERSION 0)
    set(APP_STATUS "Release")
else()
    # After tag or no tag
    if(TAG_RESULT EQUAL 0)
        string(REGEX MATCH "v([0-9]+)\\.([0-9]+)\\.([0-9]+)" _ ${LAST_TAG})
        set(APP_MAJOR_VERSION ${CMAKE_MATCH_1})
        set(APP_MINOR_VERSION ${CMAKE_MATCH_2})
        set(APP_PATCH_VERSION ${CMAKE_MATCH_3})
    else()
        set(APP_MAJOR_VERSION 0)
        set(APP_MINOR_VERSION 0)
        set(APP_PATCH_VERSION 0)
    endif()

    set(APP_DEV_VERSION ${COMMITS_SINCE_TAG})
    set(APP_STATUS "Development")
endif()

# Set final version string based on status
if(APP_STATUS STREQUAL "Release")
    set(APP_VERSION_STRING "${APP_MAJOR_VERSION}.${APP_MINOR_VERSION}.${APP_PATCH_VERSION}")
    set(APP_SHORT_COMMIT_STRING "${COMMIT_HASH_SHORT}")
else()
    set(APP_VERSION_STRING "${APP_MAJOR_VERSION}.${APP_MINOR_VERSION}.${APP_PATCH_VERSION}.${APP_DEV_VERSION}")
    set(APP_SHORT_COMMIT_STRING "Dev-${COMMIT_HASH_SHORT}")
endif()

# Generate the app_version.h file from a template string
file(GENERATE
    OUTPUT "${CMAKE_BINARY_DIR}/version/app_version.h"
    CONTENT "
#ifndef _APP_VERSION_H_
#define _APP_VERSION_H_

/*
 * This file is auto-generated by CMake during the build process.
 * Do not edit this file manually.
 */

#define APP_NAME        \"${PROJECT_NAME}\"
#define APP_VERSION     \"${APP_VERSION_STRING}\"
#define APP_COMMIT_HASH \"${APP_SHORT_COMMIT_STRING}\"
#define APP_BUILD_DATE  \"${COMMIT_DATE}\"

#define APP_MAJOR_VERSION ${APP_MAJOR_VERSION}
#define APP_MINOR_VERSION ${APP_MINOR_VERSION}
#define APP_PATCH_VERSION ${APP_PATCH_VERSION}
#define APP_DEV_VERSION   ${APP_DEV_VERSION}

#endif // _APP_VERSION_H_
"
)

# Print version info for debugging
message(STATUS "Project Version: ${APP_FULL_VERSION_STRING}")
message(STATUS "Commit Hash: ${APP_COMMIT_HASH}")
message(STATUS "Build Date: ${COMMIT_DATE}")